# Assignment 3 


## 1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [1]:
x=[1,2,'a',0,5,"ali",50]

for i in range(len(x)):
    
    if i==0:
        print (i)
        
    else:
        print("none zero")

0
none zero
none zero
none zero
none zero
none zero
none zero


In [2]:
import numpy as np
x = np.array([1, 2, 3, 4])
y=np.array([0,5,6,7])

print("Test if none of the elements of the  array is zero:")
print(np.all(x))

print("Test if none of the elements of the  array is zero:")
print(np.all(y))



Test if none of the elements of the  array is zero:
True
Test if none of the elements of the  array is zero:
False


## 2. Write a NumPy program to test whether any of the elements of a given array is non-zero.


In [3]:
import numpy as np
x = np.array([1, 0, 3, 4])
y=np.array([0,0,0,0])

out1=np.any(x)
out2=np.any(y)

print("Test if any of the elements of the  array is zero:")
print(out1)

print("Test if any of the elements of the  array is zero:")
print(out2)

Test if any of the elements of the  array is zero:
True
Test if any of the elements of the  array is zero:
False


## 3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

In [4]:
import numpy as np

A=[1,2,3,4,5,6,7]
B=[1,2,3,4,5,6,7.00001]
 
print("Equal Comparison")    
print(np.equal(A,B))

print("Equal within a tolerance Comparison")    
print(np.allclose(A,B))

Equal Comparison
[ True  True  True  True  True  True False]
Equal within a tolerance Comparison
True


## 4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [5]:
a=[0]
b=[1]
c=[5]

print(a*10)
print(b*10)
print(c*10)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


In [6]:
import numpy as np

a=np.zeros(10)
b=np.ones(10)
c=np.ones(10)*5
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Write a NumPy program to create an array of the integers from 30 to70.


In [7]:
for i in enumerate(range(41),30):
   
    print(i)


(30, 0)
(31, 1)
(32, 2)
(33, 3)
(34, 4)
(35, 5)
(36, 6)
(37, 7)
(38, 8)
(39, 9)
(40, 10)
(41, 11)
(42, 12)
(43, 13)
(44, 14)
(45, 15)
(46, 16)
(47, 17)
(48, 18)
(49, 19)
(50, 20)
(51, 21)
(52, 22)
(53, 23)
(54, 24)
(55, 25)
(56, 26)
(57, 27)
(58, 28)
(59, 29)
(60, 30)
(61, 31)
(62, 32)
(63, 33)
(64, 34)
(65, 35)
(66, 36)
(67, 37)
(68, 38)
(69, 39)
(70, 40)


In [8]:
import numpy as np

array=np.arange(30,71)
print(array)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


## 6. Write a NumPy program to create a 3x3 identity matrix 

In [9]:
import numpy as np

i = np.identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 7. Write a NumPy program to generate a random number between 0 and 1

In [10]:
import numpy as np

rand_num = np.random.normal(0,1)
print(f"The random number between 0 and 1 is  {rand_num}")


The random number between 0 and 1 is  1.466800307900916


## 8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution 

In [11]:
import numpy as np

Array = np.random.normal(0,1,15)
print(Array)

[ 1.44965087 -2.77047804 -0.93316222 -0.73995962 -0.13905509 -1.42802281
 -1.3808467  -1.42371686 -0.71023149  0.91010177 -0.07457615 -0.87363685
  1.40383383  1.38079486 -1.93942276]


## 9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [12]:
import numpy as np

vector=np.arange(16,55)
print(vector)

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [13]:
import numpy as np
vector = np.arange(15,55)
print(f"Original vector:\n {vector}")
print("--------------------------------------------------")
print(f"All values except the first and last of the said vector:\n {vector[1:]}")



Original vector:
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
--------------------------------------------------
All values except the first and last of the said vector:
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


## 10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [14]:
import numpy as np

x = np.random.randint(0, 11, 5)
print(f"Vector of length 5 filled with arbitrary integers from 0 to 10:\n {x}")



Vector of length 5 filled with arbitrary integers from 0 to 10:
 [9 6 0 6 5]


## 11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.


In [15]:
import numpy as np

x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [16]:
import numpy as np

x = np.zeros((5, 5))
x[0,0]=1
x[1,1]=2
x[2,2]=3
x[3,3]=4
x[4,4]=5

print(x)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


## 13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagona

In [17]:
import numpy as np

x = np.zeros((4, 4))

x[::2, 1::2] = 1
x[1::2, ::2] = 1

print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


## 14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.


## 15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select

## 16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number